#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrandr --output DP-2 --mode 2560x1440 --rate 144 --right-of DP-4 --output DP-4 --mode 2560x1440 --rate 144 --primary&

polybar &
picom --config ~/.config/picom/picom.conf&

##WALL PAPERS
WALLPAPER_DIR="$HOME/.local/share/wallpapers"

# Get a random wallpaper from the directory
WALLPAPER1=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)
WALLPAPER2=$(find "$WALLPAPER_DIR" -type f | shuf -n 1)

# Set the wallpapers using feh
feh --bg-scale "$WALLPAPER1" --bg-scale "$WALLPAPER2"
